volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    depends_on: 
      - postgres
    ports:
      - "4000:4000"
    restart: always

