name: Label when approved
on: pull_request_review

jobs:

  label-when-approved:
    name: "Label when approved"
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      isApprovedByCommiters: ${{ steps.label-when-approved-by-commiters.outputs.isApproved }}
      isApprovedByAnyone: ${{ steps.label-when-approved-by-anyone.outputs.isApproved }}
    steps:
      - name: Label when approved by anyone
        uses: TobKed/label-when-approved-action@v1.2
        id: label-when-approved-by-anyone
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'Ready to Merge'
          require_committers_approval: 'false'
          remove_label_when_approval_missing: 'true'
          comment: 'PR approved by at least one committer and no changes requested.'
