name: Script - npm run seed:prod
on: workflow_dispatch
jobs:
  npm-run:
    name: Execute Script
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Execute Script
        run: npm run db:textbooks ${{ github.event.inputs.term }}
