name: Check Schema Consistency

on:
  pull_request:
    branches: [ main ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Company 4 Schema
        uses: actions/checkout@v3
      - name: Clone Company 3 Schema
        run: git clone https://github.com/SENG499-S22-Company3/shared.git
      - name: Sort Schema files alphabetically
        run: |
          sort schema.graphql | tr -d "[:blank:]" | grep "\S" > c4schema.graphql
          sort shared/graphql/schema.graphql | tr -d "[:blank:]" | grep "\S" > c3schema.graphql
      - name: Compare Files
        run: diff c3schema.graphql c4schema.graphql
